/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AccountChildrenNewRouteImport } from './routes/account/children/new'
import { Route as AccountChildrenChildIdRouteImport } from './routes/account/children/$childId'
import { Route as AccountChildrenChildIdEditRouteImport } from './routes/account/children/$childId.edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountChildrenNewRoute = AccountChildrenNewRouteImport.update({
  id: '/account/children/new',
  path: '/account/children/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountChildrenChildIdRoute = AccountChildrenChildIdRouteImport.update({
  id: '/account/children/$childId',
  path: '/account/children/$childId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountChildrenChildIdEditRoute =
  AccountChildrenChildIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AccountChildrenChildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/account': typeof AccountIndexRoute
  '/account/children/$childId': typeof AccountChildrenChildIdRouteWithChildren
  '/account/children/new': typeof AccountChildrenNewRoute
  '/account/children/$childId/edit': typeof AccountChildrenChildIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/account': typeof AccountIndexRoute
  '/account/children/$childId': typeof AccountChildrenChildIdRouteWithChildren
  '/account/children/new': typeof AccountChildrenNewRoute
  '/account/children/$childId/edit': typeof AccountChildrenChildIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/account/': typeof AccountIndexRoute
  '/account/children/$childId': typeof AccountChildrenChildIdRouteWithChildren
  '/account/children/new': typeof AccountChildrenNewRoute
  '/account/children/$childId/edit': typeof AccountChildrenChildIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/account'
    | '/account/children/$childId'
    | '/account/children/new'
    | '/account/children/$childId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/account'
    | '/account/children/$childId'
    | '/account/children/new'
    | '/account/children/$childId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/account/'
    | '/account/children/$childId'
    | '/account/children/new'
    | '/account/children/$childId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountChildrenChildIdRoute: typeof AccountChildrenChildIdRouteWithChildren
  AccountChildrenNewRoute: typeof AccountChildrenNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/children/new': {
      id: '/account/children/new'
      path: '/account/children/new'
      fullPath: '/account/children/new'
      preLoaderRoute: typeof AccountChildrenNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/children/$childId': {
      id: '/account/children/$childId'
      path: '/account/children/$childId'
      fullPath: '/account/children/$childId'
      preLoaderRoute: typeof AccountChildrenChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/children/$childId/edit': {
      id: '/account/children/$childId/edit'
      path: '/edit'
      fullPath: '/account/children/$childId/edit'
      preLoaderRoute: typeof AccountChildrenChildIdEditRouteImport
      parentRoute: typeof AccountChildrenChildIdRoute
    }
  }
}

interface AccountChildrenChildIdRouteChildren {
  AccountChildrenChildIdEditRoute: typeof AccountChildrenChildIdEditRoute
}

const AccountChildrenChildIdRouteChildren: AccountChildrenChildIdRouteChildren =
  {
    AccountChildrenChildIdEditRoute: AccountChildrenChildIdEditRoute,
  }

const AccountChildrenChildIdRouteWithChildren =
  AccountChildrenChildIdRoute._addFileChildren(
    AccountChildrenChildIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountChildrenChildIdRoute: AccountChildrenChildIdRouteWithChildren,
  AccountChildrenNewRoute: AccountChildrenNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
